# Generated by Django 3.2 on 2023-08-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230817_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
